# Project: Silan3A
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = body.o main.o
LINKOBJ  = body.o main.o
LIBS     = -L"C:/Users/Asus/Dev-Cpp/TDM-GCC-64/lib" -L"C:/Users/Asus/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/Asus/Dev-Cpp/TDM-GCC-64/include" -I"C:/Users/Asus/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Users/Asus/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"C:/Users/Asus/Dev-Cpp/TDM-GCC-64/include" -I"C:/Users/Asus/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Users/Asus/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/Users/Asus/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = Silan3A.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = C:\Users\Asus\Dev-Cpp\DevCpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

body.o: body.c
	$(CPP) -c body.c -o body.o $(CXXFLAGS)

main.o: main.c
	$(CPP) -c main.c -o main.o $(CXXFLAGS)
